# Generated by Django 6.0.1 on 2026-01-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=models.CharField(default='Resumo não informado', max_length=200),
        ),
    ]
