# Generated by Django 6.0.1 on 2026-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resumo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
